name = "number-snake-analytics"
main = "src/worker.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "number-snake-analytics"
database_id = "bf757bdc-6792-4e45-bef2-34b73795570f"
